apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-nodejs
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/abhishekjv/helloworld-nodejs
            env:
              - name: MESSAGE
                value: "Version 1"
