apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: helloworld-nodejs-blue
  namespace: default
spec:
  revisionTemplate:
    spec:
      container:
        image: docker.io/abhishekjv/helloworld-nodejs
        env:
          - name: MESSAGE
            value: "BLUE"
